---
sidebar: sidebar
permalink: ONTAP/fix-blockers-warnings.html
keywords: fix ontap blockers and warnings, ontap update precheck, acknowledge warnings
summary: Fix ONTAP blockers and acknowledge warnings that are preventing you to complete the ONTAP update.
---
= Fix all blockers using software updates before an ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]
After you have identified the ONTAP target version for your ONTAP storage system, you should fix and acknowledge all blockers and review the warnings before updating the ONTAP storage system.

You must fix and acknowledge all blockers before updating the software.

.Steps

. From the Console left navigation, select *Health* > *Software updates*.
+
The Console displays the list of clusters that require a software update.
. Identify the ONTAP target version for your storage system. For information about identifying the ONTAP target version, see link:../ONTAP/choose-ontap-910-later.html[Compare ONTAP versions to understand the benefits and risks of using software updates].
. After you have decided on the ONTAP target version, select *Prepare for update* to initiate the update process.
+
The list of blockers and warnings are displayed.
. Select the blocker to view the instructions to fix the blocker.
. Manually perform the steps provided to fix the blocker.
. Select the blockers that have been fixed and select *Acknowledge selected* to acknowledge that that blockers have been fixed.

NOTE: You must fix and acknowledge all the blockers to proceed with the update.

[start=7]
. Select *Warnings* tab to review the warnings before proceeding with the software update.
. Select *Acknowledge* tab to view the blockers that have been fixed.
. Select *Continue to update* to proceed with the update process.




