---
sidebar: sidebar
permalink: get-started/software-updates.html
keywords: ontap 9.10, ontap update, supported systems for ontap update, ontap version, software updates benefits
summary: Seamlessly update your ONTAP storage system to take advantage of the new and enhanced features by using software updates.
---
= Learn about software updates
:icons: font
:imagesdir: ../media/

[.lead]

You can use software updates to enable customers streamline ONTAP updates. This can help you reduce costs, accelerate critical workloads, and improve security.

Software updates automates the assessment, planning, and execution processes. The intelligent upgrade advisor predicts which versions best fit the specific system, recommending versions to remediate issues, improves efficiencies, and increases system security, allowing customers to determine the best option to meet their needs. Then it distributes the software package and automatically executes the automated non-distributive upgrade (ANDU), independent of support services. 

== NetApp Console

Software updates is accessible through the NetApp Console.

The NetApp Console provides centralized management of NetApp storage and data services across on-premises and cloud environments at enterprise grade. The Console is required to access and use NetApp data services. As a management interface, it enables you to manage many storage resources from one interface. Console administrators can control access to storage and services for all systems within the enterprise.

You don’t need a license or subscription to start using NetApp Console and you only incur charges when you need to deploy Console agents in your cloud to ensure connectivity to your storage systems or NetApp data services. However, some NetApp data services accessible from the Console are licensed or subscription-based.

Learn more about the https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html[NetApp Console].


== Supported ONTAP systems

You can complete the ONTAP update using software updates only if you are running on ONTAP 9.10 or later versions. 

The following information provides the software update process for different ONTAP versions:   

|===
|*Current ONTAP version*  | *Update process*

|9.12 and above | All steps of ONTAP update happen within the Console.
|9.10 to 9.12  | Preparation for ONTAP update happens within the software updates screens. You will be navigated to System Manager to perform the actual ONTAP update. To execute all steps of ONTAP update within the Console, you need to link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[set up a Console agent].  
|9.8 to 9.10  | Preparation for ONTAP update happens within the software updates screens. You will be navigated to System Manager to perform the actual ONTAP update. 
|Below 9.7 | Automated ONTAP update is not supported for this cluster. You need to update ONTAP manually. For more information, see link:https://docs.netapp.com/us-en/ontap/upgrade/index.html[manually update your storage systems].

|===

== Benefits of using software updates
Updating your ONTAP storage system can help you improve the performance, security, and functionality of your storage system.

Some of the benefits of updating your ONTAP storage system are: 

* You can access the latest features and enhancements that ONTAP offers, such as new protocols, data services, and cloud integration options. 
* You can fix any bugs or vulnerabilities that may affect your system stability, reliability, or security. 
* You can optimize your system performance and efficiency by applying the latest patches and improvements. 
* You can ensure compatibility and interoperability with other NetApp products, third-party applications, and cloud providers. 
* You can benefit from the ongoing support and maintenance that NetApp provides for the latest ONTAP OS versions. 

== Cost
NetApp doesn’t charge you for using software updates.
